# -*- coding: utf-8 -*-
"""Task-11_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sNMvr5ImallRsE9laqHW7Mld_tx0PMzJ

#CSL7870: Learning on Graphs

#TASK-11 : GraphSAGE and GAT Implementation

# Anuj Rajan Lalla

# B22AI061
"""

!pip install torch_geometric

"""# Imports"""

import torch
import torch.nn.functional as F
import torch.nn as nn
from torch_geometric.nn import SAGEConv, GATConv
from torch_geometric.datasets import Planetoid
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report, precision_recall_fscore_support
import matplotlib.pyplot as plt
from torch_geometric.utils import to_undirected
import networkx as nx
import numpy as np

"""# Functions from template, initialized here"""

def setup_environment(seed=42):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print('Using device:', device)
    return device

def load_data():
    dataset = Planetoid(root='/tmp/Cora', name='Cora')  # downloads if needed
    return dataset[0]

device = setup_environment(42)
data = load_data().to(device)
num_feats = data.num_features
num_classes = int(data.y.max()) + 1
print('Features:', num_feats, '| Classes:', num_classes)

"""# Dataset EDA

## Computing diameter here to later facilitate discussion on oversmoothing and expressiveness
"""

def cora_diameter_from_pyg(data):
    # 1) make simple undirected edge list (drop self-loops if any)
    ei = to_undirected(data.edge_index)
    mask = ei[0] != ei[1]
    ei = ei[:, mask].cpu().numpy().T  # shape [E, 2]

    # 2) build simple graph in networkx
    G = nx.Graph()
    G.add_nodes_from(range(data.num_nodes))
    G.add_edges_from(map(tuple, ei))

    # 3) take the largest connected component
    if not nx.is_connected(G):
        G = G.subgraph(max(nx.connected_components(G), key=len)).copy()

    # 4) compute diameter
    d = nx.diameter(G)  # longest shortest-path length
    return d

print("Cora diameter (undirected, LCC):", cora_diameter_from_pyg(data))

"""## Class distribution"""

def undirected_edge_count(edge_index):
    # PyG stores each undirected edge twice (i->j and j->i); self-loops once.
    # Count unique unordered pairs to estimate undirected edges excluding self-loops.
    ei = edge_index.cpu().numpy()
    u = ei[0]; v = ei[1]
    mask = u <= v  # keep one direction + self loops
    pairs = list(zip(u[mask], v[mask]))
    # remove duplicates that still sneak in when u==v (self-loops counted once already)
    return len(set((int(a), int(b)) for a,b in pairs if a != b)), sum(int(a==b) for a,b in pairs)

num_nodes = data.num_nodes
num_edges_directed = data.num_edges
num_undirected, num_self_loops = undirected_edge_count(data.edge_index)
num_node_features = data.num_node_features
num_classes = int(data.y.max().item() + 1)

train_count = int(data.train_mask.sum())
val_count   = int(data.val_mask.sum())
test_count  = int(data.test_mask.sum())

print(f"Nodes: {num_nodes}")
print(f"Edges (directed rep in PyG): {num_edges_directed}")
print(f"Edges (approx undirected, excl self-loops): {num_undirected}")
print(f"Self-loops: {num_self_loops}")
print(f"Node features (dim): {num_node_features}")
print(f"Num classes: {num_classes}")
print(f"Split sizes — train: {train_count}, val: {val_count}, test: {test_count}")

labels, counts = torch.unique(data.y, return_counts=True)
df_counts = pd.DataFrame({
    "class_id": labels.cpu().numpy(),
    "count": counts.cpu().numpy()
}).sort_values("class_id", ignore_index=True)
df_counts["percent"] = (100.0 * df_counts["count"] / df_counts["count"].sum()).round(2)

imbalance_ratio = df_counts["count"].max() / df_counts["count"].min()

display(df_counts)
print(f"Imbalance ratio (max/min class count): {imbalance_ratio:.2f}x")

"""## Plot"""

plt.figure(figsize=(6,4))
plt.bar(df_counts["class_id"].astype(str), df_counts["count"])
plt.title("Cora — Class/Label Distribution")
plt.xlabel("Class ID")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

"""## Degree distribution plot"""

# Degree with PyG’s directed rep (ok for an undirected graph stored bidirectionally)
deg = torch.bincount(data.edge_index[0], minlength=num_nodes).cpu().numpy()

print(f"Avg degree: {deg.mean():.2f} | Median: {float(pd.Series(deg).median()):.0f} | Max: {deg.max()}")
plt.figure(figsize=(6,4))
plt.hist(deg, bins=30)
plt.title("Node Degree Distribution (Cora)")
plt.xlabel("Degree")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

"""# GraphSAGE as defined in the template"""

class GraphSAGE(torch.nn.Module):
    """
    GraphSAGE model implementation.
    This class can be configured with a variable number of layers and different aggregators.
    """
    def __init__(self, in_channels, hidden_channels, out_channels, num_layers=2, aggregator='mean', dropout=0.5):
        super(GraphSAGE, self).__init__()
        self.convs = torch.nn.ModuleList()

        # Input layer
        self.convs.append(SAGEConv(in_channels, hidden_channels, aggregator))

        # Hidden layers
        for _ in range(num_layers - 2):
            self.convs.append(SAGEConv(hidden_channels, hidden_channels, aggregator))

        # Output layer
        self.convs.append(SAGEConv(hidden_channels, out_channels, aggregator))

        self.dropout = dropout

    def forward(self, x, edge_index):
        for i, conv in enumerate(self.convs):
            x = conv(x, edge_index)
            # Apply activation and dropout to all but the last layer
            if i < len(self.convs) - 1:
                x = F.relu(x)
                x = F.dropout(x, p=self.dropout, training=self.training)
        return F.log_softmax(x, dim=1)

"""# GAT implementation ( Completed as defined in template )"""

class GAT(nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, num_layers=2, heads=1, dropout=0.5):
        super().__init__()
        self.convs = nn.ModuleList()
        # First layer: in -> hidden * heads (concat=True)
        self.convs.append(GATConv(in_channels, hidden_channels, heads=heads, concat=True, dropout=dropout))
        # Optional hidden layers (kept general)
        for _ in range(num_layers - 2):
            self.convs.append(GATConv(hidden_channels * heads, hidden_channels, heads=heads, concat=True, dropout=dropout))
        # Final layer: hidden * heads -> out, heads=1, concat=False (per GAT paper)
        self.convs.append(GATConv(hidden_channels * heads, out_channels, heads=1, concat=False, dropout=dropout))
        self.dropout = dropout

    def forward(self, x, edge_index):
        for i, conv in enumerate(self.convs):
            x = F.dropout(x, p=self.dropout, training=self.training)
            x = conv(x, edge_index)
            if i < len(self.convs) - 1:
                x = F.elu(x)
        return F.log_softmax(x, dim=1)

"""# Train and test functions ( Completed as defined in template )"""

def train(model, data, optimizer, criterion):
    model.train()
    optimizer.zero_grad()
    out = model(data.x, data.edge_index)
    loss = criterion(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()
    return float(loss.item())

@torch.no_grad()
def test(model, data):
    model.eval()
    out = model(data.x, data.edge_index)
    pred = out.argmax(dim=1)
    accs = []
    for mask in [data.train_mask, data.val_mask, data.test_mask]:
        correct = int((pred[mask] == data.y[mask]).sum())
        total = int(mask.sum())
        accs.append(correct / total)
    return accs  # [train_acc, val_acc, test_acc]

"""# Function for running experiment ( Already defined in template )"""

def run_experiment(model, data, device, epochs=200, lr=0.01, weight_decay=5e-4):
    """
    Runs a full training and evaluation experiment for a given model.
    (This function is complete and does not need modification).
    """
    model = model.to(device)
    data = data.to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    criterion = torch.nn.NLLLoss()

    best_val_acc = 0
    final_test_acc = 0

    for epoch in range(1, epochs + 1):
        loss = train(model, data, optimizer, criterion)
        train_acc, val_acc, test_acc = test(model, data)

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            final_test_acc = test_acc

        if epoch % 20 == 0:
            print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}, Train: {train_acc:.4f}, '
                  f'Val: {val_acc:.4f}, Test: {test_acc:.4f}')

    return final_test_acc

"""# Helper functions to facilitate more analysis

## This is similar to test function but this returns entire list of predictions and not just scalar accuracy values
"""

@torch.no_grad()
def _predict_on_mask(model, data, mask):
    model.eval()
    out  = model(data.x, data.edge_index)
    pred = out.argmax(dim=1)
    y_true = data.y[mask].detach().cpu().numpy()
    y_pred = pred[mask].detach().cpu().numpy()
    return y_true, y_pred

"""## This stores accuracy and loss values and returns them which is used for plotting"""

def run_and_log(model, data, device, epochs=200, lr=0.01, weight_decay=5e-4, print_every=20):
    """
    Drop-in runner that logs epoch loss/acc using your existing train() and test().
    No changes to your other code required.
    """
    model = model.to(device)
    data  = data.to(device)
    opt   = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    crit  = torch.nn.NLLLoss()

    history = {"epoch": [], "loss": [], "train_acc": [], "val_acc": [], "test_acc": []}
    best = {"val_acc": -1.0, "test_acc": -1.0, "state": None}

    for epoch in range(1, epochs+1):
        loss = train(model, data, opt, crit)     # your train()
        tr, va, te = test(model, data)           # your test() -> [train,val,test]

        history["epoch"].append(epoch)
        history["loss"].append(float(loss))
        history["train_acc"].append(float(tr))
        history["val_acc"].append(float(va))
        history["test_acc"].append(float(te))

        if va > best["val_acc"]:
            best["val_acc"] = va
            best["test_acc"] = te
            best["state"] = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

        if epoch % print_every == 0:
            print(f"Epoch {epoch:03d} | Loss {loss:.4f} | Train {tr:.4f} | Val {va:.4f} | Test {te:.4f}")

    # restore best-by-val weights for final evaluation/plots
    if best["state"] is not None:
        model.load_state_dict({k: v.to(device) for k, v in best["state"].items()})

    return model, history, best

"""## Helper for plotting accuracy and loss"""

def plot_curves(history, title_suffix=""):
    ep = history["epoch"]
    # loss
    plt.figure(figsize=(6,4))
    plt.plot(ep, history["loss"], label="Train loss")
    plt.xlabel("Epoch"); plt.ylabel("NLL Loss")
    plt.title(f"Loss{(' — ' + title_suffix) if title_suffix else ''}")
    plt.grid(True); plt.tight_layout(); plt.show()

    # accuracy
    plt.figure(figsize=(6,4))
    plt.plot(ep, history["train_acc"], label="Train")
    plt.plot(ep, history["val_acc"],   label="Val")
    plt.plot(ep, history["test_acc"],  label="Test")
    plt.xlabel("Epoch"); plt.ylabel("Accuracy")
    plt.title(f"Accuracy{(' — ' + title_suffix) if title_suffix else ''}")
    plt.legend(); plt.grid(True); plt.tight_layout(); plt.show()

"""## Helper for getting metrics"""

def print_test_metrics(model, data, title_suffix="", label_names=None):
    n_classes = int(data.y.max().item()) + 1
    labels_list = list(range(n_classes))

    y_true, y_pred = _predict_on_mask(model, data, data.test_mask)

    print(f"\n=== Test set metrics{(' — ' + title_suffix) if title_suffix else ''} ===")
    # Include all classes even if absent in test by specifying labels
    if label_names is not None and len(label_names) == n_classes:
        print(classification_report(y_true, y_pred, labels=labels_list,
                                    target_names=label_names, digits=4, zero_division=0))
    else:
        print(classification_report(y_true, y_pred, labels=labels_list,
                                    digits=4, zero_division=0))

    cm = confusion_matrix(y_true, y_pred, labels=labels_list)
    print("Confusion matrix (rows=true, cols=pred):")
    print(cm)

    # Heatmap
    plt.figure(figsize=(6,5))
    im = plt.imshow(cm, interpolation='nearest')
    plt.title(f"Confusion Matrix{(' — ' + title_suffix) if title_suffix else ''}")
    plt.colorbar(im, fraction=0.046, pad=0.04)
    ticklabels = label_names if (label_names and len(label_names)==n_classes) else labels_list
    plt.xticks(labels_list, ticklabels, rotation=45, ha="right")
    plt.yticks(labels_list, ticklabels)
    plt.xlabel("Predicted"); plt.ylabel("True")
    plt.tight_layout(); plt.show()
    # Per-class table
    p, r, f1, support = precision_recall_fscore_support(
        y_true, y_pred, labels=labels_list, zero_division=0
    )
    per_class_df = pd.DataFrame({
        "class_id": labels_list,
        "precision": p, "recall": r, "f1": f1, "support": support
    })
    display(per_class_df)
    return per_class_df, cm

"""# Autoencoder

## Why ?
**Because LSTM for 1433 input dimensions was giving OOM error. So as discussed in class for analyzing LSTM also I downproject the features using an Autoencoder**
"""

# ===== 1) Autoencoder definition =====
import torch
import torch.nn as nn
import torch.nn.functional as F

class AE(nn.Module):
    def __init__(self, enc_dims=(1433, 512, 128), dec_dims=None, dropout=0.0):
        super().__init__()
        if dec_dims is None:
            dec_dims = (enc_dims[-1], enc_dims[-2], enc_dims[0])
        self.enc_layers = nn.ModuleList([
            nn.Linear(enc_dims[i], enc_dims[i+1]) for i in range(len(enc_dims)-1)
        ])
        self.dec_layers = nn.ModuleList([
            nn.Linear(dec_dims[i], dec_dims[i+1]) for i in range(len(dec_dims)-1)
        ])
        self.dropout = dropout

    def encode(self, x):
        for i, lin in enumerate(self.enc_layers):
            x = lin(x)
            if i < len(self.enc_layers)-1:
                x = F.relu(x)
                if self.dropout > 0:
                    x = F.dropout(x, p=self.dropout, training=self.training)
        return x  # latent z

    def decode(self, z):
        x = z
        for i, lin in enumerate(self.dec_layers):
            x = lin(x)
            if i < len(self.dec_layers)-1:
                x = F.relu(x)
        return x

    def forward(self, x):
        z = self.encode(x)
        xr = self.decode(z)
        return xr, z

# ===== 2) Pretrain AE on node features (unsupervised) =====
@torch.no_grad()
def _standardize_cols(x):
    # Optional: column-wise standardization to help AE
    mu = x.mean(0, keepdim=True)
    sd = x.std(0, keepdim=True).clamp_min(1e-6)
    return (x - mu) / sd

def pretrain_autoencoder_features(data, proj_dim=128, epochs=100, lr=1e-3, weight_decay=1e-5, dropout=0.0, device=None):
    if device is None:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    F_in = data.x.size(1)
    ae = AE(enc_dims=(F_in, max(256, proj_dim*2), proj_dim), dropout=dropout).to(device)
    opt = torch.optim.Adam(ae.parameters(), lr=lr, weight_decay=weight_decay)
    crit = nn.MSELoss()

    x = data.x.to(device).float()
    x_std = _standardize_cols(x)  # helps reconstruction, optional

    ae.train()
    for ep in range(1, epochs+1):
        opt.zero_grad()
        xr, _ = ae(x_std)
        loss = crit(xr, x_std)
        loss.backward()
        opt.step()
        if ep % 20 == 0:
            print(f"[AE] Epoch {ep:03d} | recon MSE {loss.item():.6f}")

    ae.eval()
    return ae

# ===== 3) Replace data.x with encoder output =====
@torch.no_grad()
def apply_encoder_to_data(data, ae, device=None):
    if device is None:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    x = data.x.to(device).float()
    x_std = _standardize_cols(x)
    z = ae.encode(x_std).detach()
    data_small = data.clone()
    data_small.x = z  # shape: [N, proj_dim]
    print("Replaced features:", int(x.size(1)), "→", int(z.size(1)))
    return data_small

"""## Helper for TSNE"""

# ---- Layerwise embeddings for N-layer GNNs (GraphSAGE/GAT) ----
import torch
from collections import OrderedDict

@torch.no_grad()
def layerwise_embeddings_N(model, data, mask=None):
    """
    Returns OrderedDict: ['input', 'h1', 'h2', ..., 'final'].
    Assumes model.convs is an iterable of message-passing layers.
    Hidden layers are AFTER activation; 'final' is PRE-softmax logits.
    """
    model.eval()
    x = data.x
    ei = data.edge_index

    out = OrderedDict()
    out["input"] = x

    is_gat = "gat" in model.__class__.__name__.lower()
    act = torch.nn.functional.elu if is_gat else torch.nn.functional.relu

    assert hasattr(model, "convs"), "Expected model.convs for this utility."
    L = len(model.convs)

    for i, conv in enumerate(model.convs):
        x = conv(x, ei)
        if i < L - 1:
            x = act(x)
            out[f"h{i+1}"] = x
        else:
            out["final"] = x  # pre-softmax logits

    # mask & numpy-ify
    def to_np(t):
        t = t[mask] if mask is not None else t
        return t.detach().cpu().numpy()

    return OrderedDict((k, to_np(v)) for k, v in out.items())


def plot_tsne_all(emb_dict, labels, title_prefix="", perplexity=30, random_state=42):
    """
    Makes one t-SNE plot per entry in emb_dict (input, h1, final).
    """
    y = labels if isinstance(labels, np.ndarray) else labels.cpu().numpy()
    for name, E in emb_dict.items():
        Z = TSNE(n_components=2, init="pca", learning_rate="auto",
                 perplexity=perplexity, random_state=random_state).fit_transform(E)
        plt.figure(figsize=(5,5))
        for c in np.unique(y):
            idx = (y==c)
            plt.scatter(Z[idx,0], Z[idx,1], s=8, alpha=0.7, label=str(c))
        plt.title(f"{title_prefix} — t-SNE of {name}")
        plt.legend(title="Class", bbox_to_anchor=(1.02,1), loc="upper left")
        plt.tight_layout(); plt.show()

"""# Experiments

## 1.  Full Input features ( 1433 ) . Apart from LSTM running for all

### Hyperparameters
"""

def count_params(m): return sum(p.numel() for p in m.parameters() if p.requires_grad)

hidden = 64
dropout = 0.5
epochs = 200
lr = 0.01
weight_decay = 5e-4
num_feats = data.x.size(1)

"""### GraphSAGE ( mean, max )"""

_ = setup_environment(42)
aggregators = ['mean', 'max']  # lstm is supported by SAGEConv.  # see docs
sage_results = {}

for aggr in aggregators:
    print(f'\n=== GraphSAGE | aggr={aggr} ===')
    model = GraphSAGE(num_feats, hidden, num_classes, num_layers=2, aggregator=aggr, dropout=dropout)
    test_acc = run_experiment(model, data, device, epochs=epochs, lr=lr, weight_decay=weight_decay)
    print(f'Params (GraphSAGE full {aggr})',count_params(model))
    sage_results[aggr] = test_acc

sage_df = pd.DataFrame(
    [{'Aggregator': k, 'Test Accuracy (%)': round(v * 100, 2)} for k, v in sage_results.items()]
).sort_values('Test Accuracy (%)', ascending=False).reset_index(drop=True)

best_aggr = sage_df.loc[0, 'Aggregator']
print('\nGraphSAGE results:')
print(sage_df.to_string(index=False))
print(f'\nBest GraphSAGE aggregator: {best_aggr}')

"""### Mean aggregator gives the best result so detailed analysis"""

# use the AE-compressed features (this is what fixed LSTM for you)
data_used = data

num_feats = data_used.x.size(1)
num_classes = int(data_used.y.max()) + 1
_ = setup_environment(42)

model = GraphSAGE(num_feats, hidden, num_classes, num_layers=2, aggregator='mean', dropout=dropout)
model, history, best = run_and_log(model, data_used, device, epochs=epochs, lr=lr, weight_decay=weight_decay, print_every=20)

plot_curves(history, title_suffix="GraphSAGE (mean)")
_ = print_test_metrics(model, data_used, title_suffix="GraphSAGE (mean)")

"""### GAT ( 1 , 2 and 5 heads )"""

gat_heads_list = [1, 2, 5]  # requested variants
gat_results = {}

_ = setup_environment(42)


for heads in gat_heads_list:
    print(f'\n=== GAT | heads={heads} ===')
    model = GAT(num_feats, hidden, num_classes, num_layers=2, heads=heads, dropout=dropout)  # same hyperparams
    test_acc = run_experiment(model, data, device, epochs=epochs, lr=lr, weight_decay=weight_decay)
    print(f'Params (GAT full {heads})',count_params(model))
    gat_results[heads] = test_acc

gat_df = pd.DataFrame(
    [{'Heads': h, 'Test Accuracy (%)': round(acc * 100, 2)} for h, acc in gat_results.items()]
).sort_values('Heads').reset_index(drop=True)

print('\nGAT results:')
print(gat_df.to_string(index=False))

"""### 1 head gave best results so analysis"""

_ = setup_environment(42)

model = model = GAT(num_feats, hidden, num_classes, num_layers=2, heads=1, dropout=dropout)
model, history, best = run_and_log(model, data_used, device, epochs=epochs, lr=lr, weight_decay=weight_decay, print_every=20)

plot_curves(history, title_suffix="GAT (1 head)")
_ = print_test_metrics(model, data_used, title_suffix="GAT (1 head")

"""### Comparison"""

# Simple comparison table (best of each family)
best_gat_heads = max(gat_results, key=lambda h: gat_results[h])
compare_df = pd.DataFrame({
    'Model': ['GraphSAGE (best)', 'GAT (best)'],
    'Config': [f'Aggregator={best_aggr}', f'Heads={best_gat_heads}'],
    'Test Accuracy (%)': [round(sage_results[best_aggr]*100, 2), round(gat_results[best_gat_heads]*100, 2)]
})
print('\nComparison:')
print(compare_df.to_string(index=False))

"""## As GAT Model gives the best results I am plotting tsne plots for it to see feature discriminativeness as layers progress"""

from sklearn.manifold import TSNE
embs = layerwise_embeddings_N(model, data, mask=data.test_mask)
labels = data.y[data.test_mask]
plot_tsne_all(embs, labels, title_prefix="GAT full 2 layers (1 head)")

model = GAT(num_feats, hidden, num_classes, num_layers=15, heads=heads, dropout=dropout)  # same hyperparams
test_acc = run_experiment(model, data, device, epochs=epochs, lr=lr, weight_decay=weight_decay)

from sklearn.manifold import TSNE
embs = layerwise_embeddings_N(model, data, mask=data.test_mask)
labels = data.y[data.test_mask]
plot_tsne_all(embs, labels, title_prefix="GAT full 19 layers (1 head)")

"""## 2.  Reduced features via autoencoder ( dim = 64 )"""

proj_dim = 64
_ = setup_environment(42)

ae = pretrain_autoencoder_features(data, proj_dim=proj_dim, epochs=100, lr=1e-3, weight_decay=1e-5, dropout=0.1, device=device)
data_64 = apply_encoder_to_data(data, ae, device=device)

"""### Hyperparameters"""

hidden = 64
dropout = 0.5
epochs = 200
lr = 0.01
weight_decay = 5e-4
num_feats = data_64.x.size(1)

"""### GraphSAGE ( mean , max , lstm )"""

_ = setup_environment(42)
aggregators = ['mean', 'max','lstm']  # lstm is supported by SAGEConv.  # see docs
sage_results = {}

for aggr in aggregators:
    print(f'\n=== GraphSAGE | aggr={aggr} ===')
    model = GraphSAGE(num_feats, hidden, num_classes, num_layers=2, aggregator=aggr, dropout=dropout)
    test_acc = run_experiment(model, data_64, device, epochs=epochs, lr=lr, weight_decay=weight_decay)
    print(f'Params (GraphSAGE 64 {aggr})',count_params(model))
    sage_results[aggr] = test_acc

sage_df = pd.DataFrame(
    [{'Aggregator': k, 'Test Accuracy (%)': round(v * 100, 2)} for k, v in sage_results.items()]
).sort_values('Test Accuracy (%)', ascending=False).reset_index(drop=True)

best_aggr = sage_df.loc[0, 'Aggregator']
print('\nGraphSAGE 64 results:')
print(sage_df.to_string(index=False))
print(f'\nBest GraphSAGE aggregator: {best_aggr}')

"""### Mean gives best results"""

# use the AE-compressed features (this is what fixed LSTM for you)
data_used = data_64

num_feats = data_used.x.size(1)
num_classes = int(data_used.y.max()) + 1
_ = setup_environment(42)

model = GraphSAGE(num_feats, hidden, num_classes, num_layers=2, aggregator='mean', dropout=dropout)
model, history, best = run_and_log(model, data_used, device, epochs=epochs, lr=lr, weight_decay=weight_decay, print_every=20)

plot_curves(history, title_suffix="GraphSAGE 64 (mean)")
_ = print_test_metrics(model, data_used, title_suffix="GraphSAGE 64 (mean)")

"""### GAT ( 1, 2 and 5 heads )"""

gat_heads_list = [1, 2, 5]  # requested variants
gat_results = {}

_ = setup_environment(42)


for heads in gat_heads_list:
    print(f'\n=== GAT | heads={heads} ===')
    model = GAT(num_feats, hidden, num_classes, num_layers=2, heads=heads, dropout=dropout)  # same hyperparams
    test_acc = run_experiment(model, data_used, device, epochs=epochs, lr=lr, weight_decay=weight_decay)
    print(f'Params (GAT 64 {heads})',count_params(model))
    gat_results[heads] = test_acc

gat_df = pd.DataFrame(
    [{'Heads': h, 'Test Accuracy (%)': round(acc * 100, 2)} for h, acc in gat_results.items()]
).sort_values('Heads').reset_index(drop=True)

print('\nGAT 64 results:')
print(gat_df.to_string(index=False))

"""### 2 head gives best results"""

_ = setup_environment(42)

model = GAT(num_feats, hidden, num_classes, num_layers=2, heads=2, dropout=dropout)
model, history, best = run_and_log(model, data_used, device, epochs=epochs, lr=lr, weight_decay=weight_decay, print_every=20)

plot_curves(history, title_suffix="GAT (2 head)")
_ = print_test_metrics(model, data_used, title_suffix="GAT (2 head")

"""### Comparison"""

# Simple comparison table (best of each family)
best_gat_heads = max(gat_results, key=lambda h: gat_results[h])
compare_df = pd.DataFrame({
    'Model': ['GraphSAGE (best)', 'GAT (best)'],
    'Config': [f'Aggregator={best_aggr}', f'Heads={best_gat_heads}'],
    'Test Accuracy (%)': [round(sage_results[best_aggr]*100, 2), round(gat_results[best_gat_heads]*100, 2)]
})
print('\nComparison:')
print(compare_df.to_string(index=False))

"""## 3. Reduced features via autoencoder ( dim = 128 )"""

proj_dim = 128
_ = setup_environment(42)

ae = pretrain_autoencoder_features(data, proj_dim=proj_dim, epochs=100, lr=1e-3, weight_decay=1e-5, dropout=0.1, device=device)
data_128 = apply_encoder_to_data(data, ae, device=device)

"""### Hyperparameters"""

hidden = 64
dropout = 0.5
epochs = 200
lr = 0.01
weight_decay = 5e-4
num_feats = data_128.x.size(1)

"""### GraphSAGE ( mean , max ,lstm )"""

_ = setup_environment(42)
aggregators = ['mean', 'max','lstm']  # lstm is supported by SAGEConv.  # see docs
sage_results = {}

for aggr in aggregators:
    print(f'\n=== GraphSAGE | aggr={aggr} ===')
    model = GraphSAGE(num_feats, hidden, num_classes, num_layers=2, aggregator=aggr, dropout=dropout)
    test_acc = run_experiment(model, data_128, device, epochs=epochs, lr=lr, weight_decay=weight_decay)
    print(f'Params (GraphSAGE 128 {aggr})',count_params(model))
    sage_results[aggr] = test_acc

sage_df = pd.DataFrame(
    [{'Aggregator': k, 'Test Accuracy (%)': round(v * 100, 2)} for k, v in sage_results.items()]
).sort_values('Test Accuracy (%)', ascending=False).reset_index(drop=True)

best_aggr = sage_df.loc[0, 'Aggregator']
print('\nGraphSAGE 128 results:')
print(sage_df.to_string(index=False))
print(f'\nBest GraphSAGE aggregator: {best_aggr}')

"""### Mean gives best results"""

# use the AE-compressed features (this is what fixed LSTM for you)
data_used = data_128

num_feats = data_used.x.size(1)
num_classes = int(data_used.y.max()) + 1
_ = setup_environment(42)

model = GraphSAGE(num_feats, hidden, num_classes, num_layers=2, aggregator='mean', dropout=dropout)
model, history, best = run_and_log(model, data_used, device, epochs=epochs, lr=lr, weight_decay=weight_decay, print_every=20)

plot_curves(history, title_suffix="GraphSAGE (mean)")
_ = print_test_metrics(model, data_used, title_suffix="GraphSAGE (mean)")

"""### GAT ( 1,2 and 5 heads )"""

gat_heads_list = [1, 2, 5]  # requested variants
gat_results = {}

_ = setup_environment(42)


for heads in gat_heads_list:
    print(f'\n=== GAT | heads={heads} ===')
    model = GAT(num_feats, hidden, num_classes, num_layers=2, heads=heads, dropout=dropout)  # same hyperparams
    test_acc = run_experiment(model, data_used, device, epochs=epochs, lr=lr, weight_decay=weight_decay)
    print(f'Params (GAT 128 {heads})',count_params(model))
    gat_results[heads] = test_acc

gat_df = pd.DataFrame(
    [{'Heads': h, 'Test Accuracy (%)': round(acc * 100, 2)} for h, acc in gat_results.items()]
).sort_values('Heads').reset_index(drop=True)

print('\nGAT 128 results:')
print(gat_df.to_string(index=False))

"""### 2 head gives best results"""

_ = setup_environment(42)

model = GAT(num_feats, hidden, num_classes, num_layers=2, heads=2, dropout=dropout)
model, history, best = run_and_log(model, data_used, device, epochs=epochs, lr=lr, weight_decay=weight_decay, print_every=20)

plot_curves(history, title_suffix="GAT (2 head)")
_ = print_test_metrics(model, data_used, title_suffix="GAT (2 head")

"""### Comparison"""

# Simple comparison table (best of each family)
best_gat_heads = max(gat_results, key=lambda h: gat_results[h])
compare_df = pd.DataFrame({
    'Model': ['GraphSAGE (best)', 'GAT (best)'],
    'Config': [f'Aggregator={best_aggr}', f'Heads={best_gat_heads}'],
    'Test Accuracy (%)': [round(sage_results[best_aggr]*100, 2), round(gat_results[best_gat_heads]*100, 2)]
})
print('\nComparison:')
print(compare_df.to_string(index=False))

"""## Reduced features via autoencoder ( dim = 256 )"""

proj_dim = 256
_ = setup_environment(42)

ae = pretrain_autoencoder_features(data, proj_dim=proj_dim, epochs=100, lr=1e-3, weight_decay=1e-5, dropout=0.1, device=device)
data_256 = apply_encoder_to_data(data, ae, device=device)

"""### Hyperparameters"""

hidden = 64
dropout = 0.5
epochs = 200
lr = 0.01
weight_decay = 5e-4
num_feats = data_256.x.size(1)

"""### GraphSAGE ( mean , max , lstm )"""

_ = setup_environment(42)
aggregators = ['mean', 'max','lstm']  # lstm is supported by SAGEConv.  # see docs
sage_results = {}

for aggr in aggregators:
    print(f'\n=== GraphSAGE | aggr={aggr} ===')
    model = GraphSAGE(num_feats, hidden, num_classes, num_layers=2, aggregator=aggr, dropout=dropout)
    test_acc = run_experiment(model, data_256, device, epochs=epochs, lr=lr, weight_decay=weight_decay)
    print(f'Params (GraphSAGE 256 {aggr})',count_params(model))
    sage_results[aggr] = test_acc

sage_df = pd.DataFrame(
    [{'Aggregator': k, 'Test Accuracy (%)': round(v * 100, 2)} for k, v in sage_results.items()]
).sort_values('Test Accuracy (%)', ascending=False).reset_index(drop=True)

best_aggr = sage_df.loc[0, 'Aggregator']
print('\nGraphSAGE 256 results:')
print(sage_df.to_string(index=False))
print(f'\nBest GraphSAGE aggregator: {best_aggr}')

"""### Mean gives best results"""

# use the AE-compressed features (this is what fixed LSTM for you)
data_used = data_256

num_feats = data_used.x.size(1)
num_classes = int(data_used.y.max()) + 1
_ = setup_environment(42)

model = GraphSAGE(num_feats, hidden, num_classes, num_layers=2, aggregator='mean', dropout=dropout)
model, history, best = run_and_log(model, data_used, device, epochs=epochs, lr=lr, weight_decay=weight_decay, print_every=20)

plot_curves(history, title_suffix="GraphSAGE (mean)")
_ = print_test_metrics(model, data_used, title_suffix="GraphSAGE (mean)")

"""### GAT ( 1,2 and 5 heads )"""

gat_heads_list = [1, 2, 5]  # requested variants
gat_results = {}

_ = setup_environment(42)


for heads in gat_heads_list:
    print(f'\n=== GAT | heads={heads} ===')
    model = GAT(num_feats, hidden, num_classes, num_layers=2, heads=heads, dropout=dropout)  # same hyperparams
    test_acc = run_experiment(model, data_used, device, epochs=epochs, lr=lr, weight_decay=weight_decay)
    print(f'Params (GAT 256 {heads})',count_params(model))
    gat_results[heads] = test_acc

gat_df = pd.DataFrame(
    [{'Heads': h, 'Test Accuracy (%)': round(acc * 100, 2)} for h, acc in gat_results.items()]
).sort_values('Heads').reset_index(drop=True)

print('\nGAT 256 results:')
print(gat_df.to_string(index=False))

"""### 2 head gives bset results"""

_ = setup_environment(42)

model = GAT(num_feats, hidden, num_classes, num_layers=2, heads=2, dropout=dropout)
model, history, best = run_and_log(model, data_used, device, epochs=epochs, lr=lr, weight_decay=weight_decay, print_every=20)

plot_curves(history, title_suffix="GAT (2 head)")
_ = print_test_metrics(model, data_used, title_suffix="GAT (2 head")

"""## Comparison"""

# Simple comparison table (best of each family)
best_gat_heads = max(gat_results, key=lambda h: gat_results[h])
compare_df = pd.DataFrame({
    'Model': ['GraphSAGE (best)', 'GAT (best)'],
    'Config': [f'Aggregator={best_aggr}', f'Heads={best_gat_heads}'],
    'Test Accuracy (%)': [round(sage_results[best_aggr]*100, 2), round(gat_results[best_gat_heads]*100, 2)]
})
print('\nComparison:')
print(compare_df.to_string(index=False))